(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self;function d(b,m){b=b.split(".");var c=a;b[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===m?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=m}function f(b){return b};var g={},MSG_TRANSLATE="D\u1ecbch";g[0]=MSG_TRANSLATE;var MSG_CANCEL="H\u1ee7y";g[1]=MSG_CANCEL;var MSG_CLOSE="\u0110\u00f3ng";g[2]=MSG_CLOSE;function MSGFUNC_PAGE_TRANSLATED_TO(b){return"Google \u0111\u00e3 t\u1ef1 \u0111\u1ed9ng d\u1ecbch trang n\u00e0y sang: "+b}g[3]=MSGFUNC_PAGE_TRANSLATED_TO;function MSGFUNC_TRANSLATED_TO(b){return"\u0110\u01b0\u1ee3c d\u1ecbch sang: "+b}g[4]=MSGFUNC_TRANSLATED_TO;var MSG_GENERAL_ERROR="L\u1ed7i: M\u00e1y ch\u1ee7 kh\u00f4ng th\u1ec3 ho\u00e0n t\u1ea5t y\u00eau c\u1ea7u c\u1ee7a b\u1ea1n. Vui l\u00f2ng th\u1eed l\u1ea1i sau.";
g[5]=MSG_GENERAL_ERROR;var MSG_LEARN_MORE="Ti\u0300m hi\u00ea\u0309u th\u00eam";g[6]=MSG_LEARN_MORE;function MSGFUNC_POWERED_BY(b){return"\u0110\u01b0\u1ee3c h\u1ed7 tr\u1ee3 b\u1edfi "+b}g[7]=MSGFUNC_POWERED_BY;var MSG_TRANSLATE_PRODUCT_NAME="D\u1ecbch";g[8]=MSG_TRANSLATE_PRODUCT_NAME;var MSG_TRANSLATION_IN_PROGRESS="\u0110ang d\u1ecbch";g[9]=MSG_TRANSLATION_IN_PROGRESS;function MSGFUNC_TRANSLATE_PAGE_TO(b){return"D\u1ecbch trang n\u00e0y sang: "+(b+" b\u1eb1ng Google D\u1ecbch?")}g[10]=MSGFUNC_TRANSLATE_PAGE_TO;
function MSGFUNC_VIEW_PAGE_IN(b){return"Xem trang n\u00e0y b\u1eb1ng: "+b}g[11]=MSGFUNC_VIEW_PAGE_IN;var MSG_RESTORE="Hi\u1ec3n th\u1ecb v\u0103n b\u1ea3n g\u1ed1c";g[12]=MSG_RESTORE;var MSG_SSL_INFO_LOCAL_FILE="N\u1ed9i dung c\u1ee7a t\u1ec7p c\u1ee5c b\u1ed9 n\u00e0y s\u1ebd \u0111\u01b0\u1ee3c g\u1eedi t\u1edbi Google \u0111\u1ec3 d\u1ecbch th\u00f4ng qua m\u1ed9t k\u1ebft n\u1ed1i an to\u00e0n.";g[13]=MSG_SSL_INFO_LOCAL_FILE;var MSG_SSL_INFO_SECURE_PAGE="N\u1ed9i dung c\u1ee7a trang b\u1ea3o m\u1eadt n\u00e0y s\u1ebd \u0111\u01b0\u1ee3c g\u1eedi t\u1edbi Google \u0111\u1ec3 d\u1ecbch th\u00f4ng qua m\u1ed9t k\u1ebft n\u1ed1i an to\u00e0n.";
g[14]=MSG_SSL_INFO_SECURE_PAGE;var MSG_SSL_INFO_INTRANET_PAGE="N\u1ed9i dung c\u1ee7a trang m\u1ea1ng n\u1ed9i b\u1ed9 n\u00e0y s\u1ebd \u0111\u01b0\u1ee3c g\u1eedi t\u1edbi Google \u0111\u1ec3 d\u1ecbch th\u00f4ng qua m\u1ed9t k\u1ebft n\u1ed1i an to\u00e0n.";g[15]=MSG_SSL_INFO_INTRANET_PAGE;var MSG_SELECT_LANGUAGE="Ch\u1ecdn Ng\u00f4n ng\u1eef";g[16]=MSG_SELECT_LANGUAGE;function MSGFUNC_TURN_OFF_TRANSLATION(b){return"T\u1eaft d\u1ecbch "+b}g[17]=MSGFUNC_TURN_OFF_TRANSLATION;
function MSGFUNC_TURN_OFF_FOR(b){return"T\u1eaft \u0111\u1ed1i v\u1edbi: "+b}g[18]=MSGFUNC_TURN_OFF_FOR;var MSG_ALWAYS_HIDE_AUTO_POPUP_BANNER="Lu\u00f4n \u1ea9n";g[19]=MSG_ALWAYS_HIDE_AUTO_POPUP_BANNER;var MSG_ORIGINAL_TEXT="V\u0103n b\u1ea3n g\u1ed1c:";g[20]=MSG_ORIGINAL_TEXT;var MSG_FILL_SUGGESTION="\u0110\u00f3ng g\u00f3p b\u1ea3n d\u1ecbch hay h\u01a1n";g[21]=MSG_FILL_SUGGESTION;var MSG_SUBMIT_SUGGESTION="\u0110\u00f3ng g\u00f3p";g[22]=MSG_SUBMIT_SUGGESTION;var MSG_SHOW_TRANSLATE_ALL="D\u1ecbch t\u1ea5t c\u1ea3";
g[23]=MSG_SHOW_TRANSLATE_ALL;var MSG_SHOW_RESTORE_ALL="Kh\u00f4i ph\u1ee5c t\u1ea5t c\u1ea3";g[24]=MSG_SHOW_RESTORE_ALL;var MSG_SHOW_CANCEL_ALL="H\u1ee7y t\u1ea5t c\u1ea3";g[25]=MSG_SHOW_CANCEL_ALL;var MSG_TRANSLATE_TO_MY_LANGUAGE="D\u1ecbch c\u00e1c ph\u1ea7n sang ng\u00f4n ng\u1eef c\u1ee7a t\u00f4i";g[26]=MSG_TRANSLATE_TO_MY_LANGUAGE;function MSGFUNC_TRANSLATE_EVERYTHING_TO(b){return"D\u1ecbch m\u1ecdi th\u1ee9 sang "+b}g[27]=MSGFUNC_TRANSLATE_EVERYTHING_TO;var MSG_SHOW_ORIGINAL_LANGUAGES="Hi\u1ec3n th\u1ecb ng\u00f4n ng\u1eef g\u1ed1c";
g[28]=MSG_SHOW_ORIGINAL_LANGUAGES;var MSG_OPTIONS="T\u00f9y ch\u1ecdn";g[29]=MSG_OPTIONS;var MSG_TURN_OFF_TRANSLATION_FOR_THIS_SITE="T\u1eaft t\u00ednh n\u0103ng d\u1ecbch cho trang web n\u00e0y";g[30]=MSG_TURN_OFF_TRANSLATION_FOR_THIS_SITE;g[31]=null;var MSG_ALT_SUGGESTION="Hi\u1ec3n th\u1ecb b\u1ea3n d\u1ecbch thay th\u1ebf";g[32]=MSG_ALT_SUGGESTION;var MSG_ALT_ACTIVITY_HELPER_TEXT="Nh\u1ea5p v\u00e0o c\u00e1c t\u1eeb b\u00ean tr\u00ean \u0111\u1ec3 l\u1ea5y c\u00e1c b\u1ea3n d\u1ecbch thay th\u1ebf";
g[33]=MSG_ALT_ACTIVITY_HELPER_TEXT;var MSG_USE_ALTERNATIVES="S\u1eed d\u1ee5ng";g[34]=MSG_USE_ALTERNATIVES;var MSG_DRAG_TIP="K\u00e9o b\u1eb1ng ph\u00edm shift \u0111\u1ec3 s\u1eafp x\u1ebfp l\u1ea1i";g[35]=MSG_DRAG_TIP;var MSG_CLICK_FOR_ALT="Nh\u1ea5p \u0111\u1ec3 xem b\u1ea3n d\u1ecbch thay th\u1ebf";g[36]=MSG_CLICK_FOR_ALT;var MSG_DRAG_INSTUCTIONS="Gi\u1eef ph\u00edm Shift, nh\u1ea5p chu\u1ed9t v\u00e0 k\u00e9o c\u00e1c t\u1eeb \u1edf tr\u00ean \u0111\u1ec3 s\u1eafp x\u1ebfp l\u1ea1i.";g[37]=MSG_DRAG_INSTUCTIONS;
var MSG_SUGGESTION_SUBMITTED="C\u1ea3m \u01a1n b\u1ea1n \u0111\u00e3 \u0111\u00f3ng g\u00f3p \u0111\u1ec1 xu\u1ea5t b\u1ea3n d\u1ecbch cho Google D\u1ecbch.";g[38]=MSG_SUGGESTION_SUBMITTED;var MSG_MANAGE_TRANSLATION_FOR_THIS_SITE="Qu\u1ea3n l\u00fd b\u1ea3n d\u1ecbch cho trang web n\u00e0y";g[39]=MSG_MANAGE_TRANSLATION_FOR_THIS_SITE;var MSG_ALT_AND_CONTRIBUTE_ACTIVITY_HELPER_TEXT="Nh\u1ea5p v\u00e0o m\u1ed9t t\u1eeb \u0111\u1ec3 xem b\u1ea3n d\u1ecbch thay th\u1ebf ho\u1eb7c nh\u1ea5p \u0111\u00fap \u0111\u1ec3 ch\u1ec9nh s\u1eeda tr\u1ef1c ti\u1ebfp";
g[40]=MSG_ALT_AND_CONTRIBUTE_ACTIVITY_HELPER_TEXT;var MSG_ORIGINAL_TEXT_NO_COLON="V\u0103n b\u1ea3n g\u1ed1c";g[41]=MSG_ORIGINAL_TEXT_NO_COLON;g[42]="D\u1ecbch";g[43]="D\u1ecbch";g[44]="N\u1ed9i dung s\u1eeda \u0111\u1ed5i c\u1ee7a b\u1ea1n \u0111\u00e3 \u0111\u01b0\u1ee3c g\u1eedi.";var MSG_LANGUAGE_UNSUPPORTED="L\u1ed7i: Trang web kh\u00f4ng h\u1ed7 tr\u1ee3 ng\u00f4n ng\u1eef n\u00e0y.";g[45]=MSG_LANGUAGE_UNSUPPORTED;var MSG_LANGUAGE_TRANSLATE_WIDGET="Ti\u1ec7n \u00edch d\u1ecbch ng\u00f4n ng\u1eef";
g[46]=MSG_LANGUAGE_TRANSLATE_WIDGET;var h;function k(b,m){this.g=m===l?b:""}k.prototype.toString=function(){return this.g+""};var l={};var n=window.google&&google.translate&&google.translate._const;
if(n){var p;a:{for(var q=[],r=[""],t=0;t<r.length;++t){var u=r[t].split(","),v=u[0];if(v){var w=Number(u[1]);if(!(!w||.1<w||0>w)){var x=Number(u[2]),y=new Date,z=1E4*y.getFullYear()+100*(y.getMonth()+1)+y.getDate();!x||x<z||q.push({version:v,ratio:w,h:x})}}}var A=0,B=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),C=Number(B&&B[1])||Math.random();for(t=0;t<q.length;++t){var D=q[t];A+=D.ratio;if(1<=A)break;if(C<A){p=D.version;break a}}p="TE_20210503_00"}var E="/element/%s/e/js/element/element_main.js".replace("%s",
p);if("0"==p){var F=" element %s e js element element_main.js".split(" ");F[F.length-1]="main_vi.js";E=F.join("/").replace("%s",p)}if(n._cjlc)n._cjlc(n._pas+n._pah+E);else{var G=n._pas+n._pah+E,H,I="SCRIPT",J=document;I=String(I);"application/xhtml+xml"===J.contentType&&(I=I.toLowerCase());H=J.createElement(I);H.type="text/javascript";H.charset="UTF-8";var K,L;if(void 0===h){var M=null,N=a.trustedTypes;if(N&&N.createPolicy){try{M=N.createPolicy("goog#html",{createHTML:f,createScript:f,createScriptURL:f})}catch(b){a.console&&
a.console.error(b.message)}h=M}else h=M}var O=(L=h)?L.createScriptURL(G):G;K=new k(O,l);H.src=K instanceof k&&K.constructor===k?K.g:"type_error:TrustedResourceUrl";var P,Q,R=(H.ownerDocument&&H.ownerDocument.defaultView||window).document,S=null===(Q=R.querySelector)||void 0===Q?void 0:Q.call(R,"script[nonce]");(P=S?S.nonce||S.getAttribute("nonce")||"":"")&&H.setAttribute("nonce",P);var T=document.getElementsByTagName("head")[0];T||(T=document.body.parentNode.appendChild(document.createElement("head")));
T.appendChild(H)}d("google.translate.m",g);d("google.translate.v",p)};}).call(window)
